### ISSUE TITLE
Prop not rotating

### ISSUE THREAD

**Issue by DFliyerz** [ThatFatKidsMom/Avatar-Prop#11]
Tried remaking my prop system from v1.0.7 using v1.1.0, but the props are stuck in one rotation. The debug screen shows it as being stuck in the expansion state.

**Comment by ThatFatKidsMom** [comment]
Are you doing this in a preexisting project or in a new one? Have you tried using the newest version of the prefab in a new project yet? If it is a new project, can you check which of the conditions is not being met in order to transition out the expansion state?

**Comment by DFliyerz** [comment]
Turns out I messed something up in the fx layer transfer, redoing it fixed the problem. My bad!
