### ISSUE TITLE
Rotation seems to be broken after VRC update

### ISSUE THREAD

**Issue by DFliyerz** [ThatFatKidsMom/Avatar-Prop#13]
The rotation tracking seems to be broken after VRC updated to use their own constraints. All I can see in terms of the debug menu is that the animator layer stays at "Expansion and hand check" whenever the prop is grabbed.

EDIT: Oddly enough it seems to actually have been caused by your update rather than the VRC update, since avatars uploaded with older versions of the addon seem to work as well as can be expected.

**Comment by DFliyerz** [comment]
Even with the older version I'm seeing that rotation isn't being tracked with the left hand but only the right, and the rotation changes slightly when the prop is let go of.

**Comment by ThatFatKidsMom** [comment]
Just tested it in a clean project and everything seems fine with both the in game auto conversion and manual conversion to VRC constraints. Do you have an avatar ID of whatever is giving you issues so i can gander at it.

**Comment by DFliyerz** [comment]
I figured out that it was because I have the prop offset slightly from the grab point to make it so it doesn't clip with the hand, but the recievers that check to see which hand is grabbing weren't always reading the hand correctly if I grabbed in the wrong place. I was able to fix it by expanding those recievers.
