### ISSUE TITLE
Script missing

### ISSUE THREAD

**Issue by friesofdoom** [ThatFatKidsMom/Avatar-Prop#6]
game object "Avatar Prop/Rotation/Get Rotation/Rotation" uses missing script

You are trying to replace or create a Prefab from the instance 'Rotation' that references a missing script. This is not allowed.
Please change the script or remove it from the GameObject.
UnityEditor.PrefabUtility:SaveAsPrefabAsset (UnityEngine.GameObject,string)
VRC.SDK3.Builder.VRCAvatarBuilder:ExportCurrentAvatarResource (UnityEngine.Object,bool)
VRC.SDK3.Builder.VRCAvatarBuilder:ExportAndUploadAvatarBlueprint (UnityEngine.GameObject)
VRC.SDKBase.Editor.VRC_SdkBuilder:ExportAndUploadAvatarBlueprint (UnityEngine.GameObject)
VRC.SDK3.Editor.VRCSdkControlPanelAvatarBuilder3A:OnGUIAvatar (VRC.SDKBase.VRC_AvatarDescriptor) (at Assets/Dependencies/VRCSDK/SDK3A/Editor/VRCSdkControlPanelAvatarBuilder3A.cs:582)
VRC.SDKBase.Editor.VRCSdkControlPanelAvatarBuilder:ShowBuilder () (at Assets/Dependencies/VRCSDK/Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelAvatarBuilder.cs:159)

**Comment by ThatFatKidsMom** [comment]
Import the assets listed in the prerequisites section of the README

**Comment by friesofdoom** [comment]
I have

**Comment by friesofdoom** [comment]
![image](https://user-images.githubusercontent.com/39125557/192410188-6b5d4db2-ccb9-47f2-8ca6-0201ebe1a400.png)

**Comment by friesofdoom** [comment]
![image](https://user-images.githubusercontent.com/39125557/192410409-193d674c-4735-486f-a98b-27179a251afd.png)

**Comment by ThatFatKidsMom** [comment]
There are multiple packages you need to import. Assuming you imported all three of them then you would need to delete the old prefab from your scene since it does not have the script that the error is referring to and then place a fresh prefab back into your scene from the assets window.

**Comment by friesofdoom** [comment]
![image](https://user-images.githubusercontent.com/39125557/192410482-cf021b56-f536-4fdc-8cc7-3e7f546f1111.png)

**Comment by friesofdoom** [comment]
3? there are only 2 prerequisites listed?

**Comment by ThatFatKidsMom** [comment]
3 total. The 2 prerequisites and my own package.

**Comment by friesofdoom** [comment]
Re-adding the prefab fixed it, thanks for the help :)
