### ISSUE TITLE
Prop rotation changes when releasing prop

### ISSUE THREAD

**Issue by friesofdoom** [ThatFatKidsMom/Avatar-Prop#8]
When I let go of the prop, the rotation is often nowhere near where it was before I dropped it. Is this the case for everyone or is it something I broke in my integration?

**Comment by ThatFatKidsMom** [comment]
That would be something on your end. The prefab by default it should behave like how it does in this video: https://youtu.be/B7_FRgyEBcE

**Comment by ThatFatKidsMom** [comment]
You should try using the prefab vanilla and make sure everything is working there and then start customizing it.

Also its not necessary or related to your issue but I updated prefab just now and it should make the prop more consistent when in use.

**Comment by friesofdoom** [comment]
It mostly behaves like that, and if i hold it still for a second before letting go it ends up with the correct orientation, like something has to sync first.
I'll try the new prefab

**Comment by ThatFatKidsMom** [comment]
If your letting go very very quickly after grabbing it s then rotation could be off then. When you first grab the prop a few objects need to lock onto your avatars hand and then position themselves a certain way as thats how it gets the rotation of your hand. It only take like half a second at most for that to occur but if you were to let go before that happens then it could have a random orientation.

**Comment by friesofdoom** [comment]
When I import the latest release package, do I need to delete the prop on my avatar and re-create it, or will it update the instances in the scene automatically?

**Comment by ThatFatKidsMom** [comment]
You would need to redo the entire installation procedure after first removing it from your avatar. That includes the layers and parameters added to your fx controller. Again I recommend installing it without any customization so that you can ensure it’s behaving as it should and then once it is confirmed working customize it from there.

**Comment by friesofdoom** [comment]
What do you mean by customization? I just installed it last time and it was being a bit janky, but certainly better than nothing :>

**Comment by friesofdoom** [comment]
The new prefab does seem to work a lot better, still occasionally drops the item at the wrong angle
